version: "3.3"
services:
  postgresql:
    image: deewee_postgresql:latest
    env_file: ./additional_containers/postgresql/env
    container_name: deewee_postgresql
    ports:
      - "5432:5432"
    networks: 
      - backend
  ldap:
    image: sc_openldap:latest
    env_file: ./additional_containers/openldap/env
    container_name: archief_ldap
    ports:
      - "8389:8389"
    networks: 
      - backend
  application:
    build: .
    image: ldap2deewee:latest
    container_name: ldap2deewee
    depends_on:
      - postgresql
      - ldap
    networks: 
      - backend
networks:
  backend:
    driver: bridge
