from random import choices
from string import ascii_lowercase, digits
import webbrowser
import os
import signal
from typing import Optional
from contextlib import asynccontextmanager

import requests
import psycopg2
from fastapi import FastAPI
from requests import PreparedRequest
from pydantic import SecretStr

from models import TL_Auth
from database import save_tokens_to_database


REDIRECT_URL = "https://127.0.0.1:8000/oauth"

####################
# Helper functions #
####################


def get_random_state():
    chars = choices(ascii_lowercase + digits, k=100)
    return "".join(chars)


def open_authorization_url(state: str):
    """
    Start the authorization flow by redirecting to the Teamleader authorization page
    as described in the [Teamleader documentation](https://developer.teamleader.eu/#/introduction/authentication/authorization-flow)
    """

    req = PreparedRequest()
    req.prepare_url(
        "https://focus.teamleader.eu/oauth2/authorize",
        {
            "client_id": os.environ["TL_CLIENT_ID"],
            "response_type": "code",
            "state": state,
            "redirect_uri": REDIRECT_URL,
        },
    )

    if req.url == None:
        raise Exception("Could not create authorization url")

    print(f"\nOpen this URL in your webbrowser: \n\n{req.url}\n\n")
    webbrowser.open(req.url)


def get_access_token_from_teamleader(code: str):
    """
    After the user has granded authorization through the webbrowser, a access code is requested from Teamleader.
    """
    response = requests.post(
        "https://focus.teamleader.eu/oauth2/access_token",
        data={
            "client_id": os.environ["TL_CLIENT_ID"],
            "client_secret": os.environ["TL_CLIENT_SECRET"],
            "code": code,
            "grant_type": "authorization_code",
            "redirect_uri": REDIRECT_URL,
        },
    )

    if response.status_code != 200:
        raise Exception(f"Status code {response.status_code} - {response.reason}")

    response = response.json()
    return response


def connect_database():
    return psycopg2.connect(
        user=os.environ["POSTGRES_USERNAME"],
        password=os.environ["POSTGRES_PASSWORD"],
        host=os.environ["POSTGRES_HOST"],
        port=os.environ["POSTGRES_PORT"],
        dbname=os.environ["POSTGRES_DATABASE"],
    )


###############
# Main script #
###############

"""
The user is immediatly redirected to the Teamleader authorization page on server startup.
If the user grands authorization, Teamleader will redirect the user to a route
which will request a access token and save it to the etl_harvest database.  

See https://developer.teamleader.eu/#/introduction/authentication for more info around authorization.
"""


global_state = {}


@asynccontextmanager
async def lifespan(_: FastAPI):
    global_state["state"] = get_random_state()
    open_authorization_url(global_state["state"])
    yield


app = FastAPI(lifespan=lifespan)


@app.get("/oauth")
async def authorize(
    code: Optional[str] = None,
    state: Optional[str] = None,
    error: Optional[str] = None,
):

    if error is not None:
        raise Exception(error)

    if code is None or state is None:
        return {"error": "Either code or state was not given."}

    if state != global_state["state"]:
        return {
            "error": "The state generated by this server and state returned from Teamleader do not match which might indicate tampering."
        }

    try:
        tokens = get_access_token_from_teamleader(code)
        conn = connect_database()
        auth = TL_Auth(
            uri="https://focus.teamleader.eu/oauth2",
            client_id=os.environ["TL_CLIENT_ID"],
            client_secret=SecretStr(os.environ["TL_CLIENT_SECRET"]),
            refresh_token=SecretStr(tokens["refresh_token"]),
            access_token=SecretStr(tokens["access_token"]),
        )
        save_tokens_to_database(auth, conn)
    except Exception as e:
        return {"error": str(e)}

    print("\n\nSucces - fetched tokens from Teamleader and saved to database\n")
    os.kill(os.getpid(), signal.SIGTERM)
    return {"message": "Succes - fetched tokens from Teamleader and saved to database"}


if __name__ == "__main__":

    import uvicorn
    import subprocess

    # Generate a certificate so that the local server can be served with HTTPS.
    if not os.path.exists("key.pem") or not os.path.exists("cert.pem"):
        subprocess.run(
            [
                "openssl",
                "req",
                "-x509",
                "-newkey",
                "rsa:4096",
                "-keyout",
                "key.pem",
                "-out",
                "cert.pem",
                "-sha256",
                "-days",
                "365",
                "-nodes",
                "-subj",
                "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=CommonNameOrHostname",
            ]
        )

    uvicorn.run(
        "authorization:app",
        host="127.0.0.1",
        port=8000,
        ssl_certfile="cert.pem",
        ssl_keyfile="key.pem",
    )
