apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "web-app"
  name: "teamleader2db"
  labels:
    app: "teamleader2db"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "teamleader2db-${env}"
      namespace: "etl"
      labels:
        app: "teamleader2db"
        app.kubernetes.io/component: "teamleader2db-${env}"
        app.kubernetes.io/instance: "teamleader2db-${env}"
        app.kubernetes.io/name: "teamleader2db"
        app.kubernetes.io/part-of: "teamleader2db"
        app.openshift.io/runtime: "teamleader2db"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "teamleader2db-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      name: "teamleader2db-${env}"
      namespace: "etl"
      labels:
        app: "teamleader2db"
        app.kubernetes.io/component: "teamleader2db-${env}"
        app.kubernetes.io/instance: "teamleader2db-${env}"
        app.kubernetes.io/name: "teamleader2db"
        app.kubernetes.io/part-of: "teamleader2db"
        app.openshift.io/runtime: "teamleader2db"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "teamleader2db-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "teamleader2db-${env}"
            deploymentconfig: "teamleader2db-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "teamleader2db-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              readinessProbe:
                tcpSocket:
                  port: ${{svc_port}}
                initialDelaySeconds: 10
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "teamleader2db-${env}"
                - secretRef:
                    name: "teamleader2db-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/etl/teamleader2db:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "teamleader2db-${env}"
      namespace: "etl"
      labels:
        app: "teamleader2db"
        app.kubernetes.io/component: "teamleader2db-${env}"
        app.kubernetes.io/instance: "teamleader2db-${env}"
        app.kubernetes.io/name: "teamleader2db"
        app.kubernetes.io/part-of: "teamleader2db"
        app.openshift.io/runtime: "teamleader2db"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      TEAMLEADER_AUTH_URI: some_value
      TEAMLEADER_API_URI: some_value
      POSTGRESQL_DATABASE: some_value
      POSTGRESQL_HOST: some_value
      POSTGRESQL_PORT: some_value
      POSTGRESQL_SSLMODE: some_value
      OAUTH_TABLE: some_value
      COMPANIES_TABLE: some_value
      CONTACTS_TABLE: some_value
      DEPARTMENTS_TABLE: some_value
      EVENTS_TABLE: some_value
      INVOICES_TABLE: some_value
      PROJECTS_TABLE: some_value
      USERS_TABLE: some_value
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "teamleader2db-${env}"
      namespace: "etl"
      labels:
        app: "teamleader2db"
        app.kubernetes.io/component: "teamleader2db-${env}"
        app.kubernetes.io/instance: "teamleader2db-${env}"
        app.kubernetes.io/name: "teamleader2db"
        app.kubernetes.io/part-of: "teamleader2db"
        app.openshift.io/runtime: "teamleader2db"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    stringData:
      TEAMLEADER_CLIENT_ID: ''
      TEAMLEADER_CLIENT_SECRET: ''
      TEAMLEADER_REDIRECT_URI: ''
      TEAMLEADER_SECRET_CODE_STATE: ''
      TEAMLEADER_CODE: ''
      TEAMLEADER_AUTH_TOKEN: ''
      TEAMLEADER_REFRESH_TOKEN: ''
      POSTGRESQL_PASSWORD: ''
      POSTGRESQL_USER: ''
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"